ekyna_mailing_recipient_admin_home:
    path: ""
    defaults: { _controller: "ekyna_mailing.recipient.controller:homeAction" }
    methods: [GET]

ekyna_mailing_recipient_admin_list:
    path: /list
    defaults: { _controller: "ekyna_mailing.recipient.controller:listAction" }
    methods: [GET|POST]

ekyna_mailing_recipient_admin_new:
    path: /new
    defaults: { _controller: "ekyna_mailing.recipient.controller:newAction" }
    methods: [GET|POST]

ekyna_mailing_recipient_admin_show:
    path: /{recipientId}/show
    defaults: { _controller: "ekyna_mailing.recipient.controller:showAction" }
    methods: [GET]
    requirements:
        recipientId: \d+

ekyna_mailing_recipient_admin_edit:
    path: /{recipientId}/edit
    defaults: { _controller: "ekyna_mailing.recipient.controller:editAction" }
    methods: [GET|POST]
    requirements:
        recipientId: \d+

ekyna_mailing_recipient_admin_remove:
    path: /{recipientId}/remove
    defaults: { _controller: "ekyna_mailing.recipient.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        recipientId: \d+

ekyna_mailing_recipient_admin_search:
    path: /search
    defaults: { _controller: "ekyna_mailing.recipient.controller:searchAction" }
    methods: [GET]
    options:
        expose: true

ekyna_mailing_recipient_admin_find:
    path: /find
    defaults: { _controller: "ekyna_mailing.recipient.controller:findAction" }
    methods: [GET]
    options:
        expose: true