ekyna_mailing_recipient_list_admin_home:
    path: ""
    defaults: { _controller: "ekyna_mailing.recipient_list.controller:homeAction" }
    methods: [GET]

ekyna_mailing_recipient_list_admin_list:
    path: /list
    defaults: { _controller: "ekyna_mailing.recipient_list.controller:listAction" }
    methods: [GET|POST]

ekyna_mailing_recipient_list_admin_new:
    path: /new
    defaults: { _controller: "ekyna_mailing.recipient_list.controller:newAction" }
    methods: [GET|POST]

ekyna_mailing_recipient_list_admin_show:
    path: /{recipientListId}/show
    defaults: { _controller: "ekyna_mailing.recipient_list.controller:showAction" }
    methods: [GET|POST]
    requirements:
        recipientListId: \d+

ekyna_mailing_recipient_list_admin_recipients_unlink:
    path: /{recipientListId}/recipients/{recipientId}/unlink
    defaults: { _controller: "ekyna_mailing.recipient_list.controller:unlinkRecipientAction" }
    methods: [GET|POST]
    requirements:
        recipientListId: \d+
        recipientId: \d+

ekyna_mailing_recipient_list_admin_edit:
    path: /{recipientListId}/edit
    defaults: { _controller: "ekyna_mailing.recipient_list.controller:editAction" }
    methods: [GET|POST]
    requirements:
        recipientListId: \d+

ekyna_mailing_recipient_list_admin_remove:
    path: /{recipientListId}/remove
    defaults: { _controller: "ekyna_mailing.recipient_list.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        recipientListId: \d+
