fos_elastica:
    indexes:
        search:
            types:
                ekyna_mailing_recipient:
                    _all: {enabled: false}
                    dynamic_templates:
                        default:
                            match_mapping_type: string
                            mapping: {type: string, search_analyzer: search, index_analyzer: index}
                    persistence:
                        driver: orm
                        model: %ekyna_mailing.recipient.class%
                        provider:
                            batch_size: 25
                        listener: ~
                        finder: ~
                        repository: Ekyna\Bundle\MailingBundle\Search\RecipientRepository
