ekyna_mailing_campaign_admin:
    resource: "admin/campaign.yml"
    prefix:   /campaigns

ekyna_mailing_recipient_list_admin:
    resource: "admin/recipient_list.yml"
    prefix:   /recipient-lists

ekyna_mailing_recipient_admin:
    resource: "admin/recipient.yml"
    prefix:   /recipients
